import React, { useState } from 'react';
import { ChevronDown, Info } from 'lucide-react';

const FaqSection = () => {
  const [openIndex, setOpenIndex] = useState(null);

  const toggleFaq = (index) => {
    setOpenIndex(openIndex === index ? null : index);
  };

  const faqs = [
    {
      question: "How do I get my login credentials?",
      answer: "To guarantee security and restrict access exclusively to verified college members, self-registration is disabled. The hostel Admin or Warden registers students and staff. Your initial credentials (Enrollment Number for students, Employee ID/Phone for staff/wardens) are generated by the administration and provided to you."
    },
    {
      question: "Why can't I sign up on my own?",
      answer: "This is a closed, secure campus management portal. By requiring administrative registration, we ensure that only active students and staff of the college can access the platform, keeping the hostel databases, complaints, and student directories completely secure from external access."
    },
    {
      question: "How is a complaint resolved once filed?",
      answer: "Once a student files a complaint, it appears on the Warden's dashboard. The Warden assigns the task to the relevant maintenance staff (e.g., electrician, plumber). Once resolved, the staff marks it complete, which updates the status on both the student and warden panels in real-time."
    },
    {
      question: "How can I change my password or pin?",
      answer: "Once logged in, navigate to your dashboard and click the 'Change Password' tab. We strongly recommend changing your default, admin-provided password or PIN immediately after your first successful login."
    },
    {
      question: "Who should I contact for portal support?",
      answer: "If you cannot login, have not received your credentials, or face technical issues, please contact your hostel Warden's office or send an email to the college IT Helpdesk."
    }
  ];

  return (
    <section className="w-full py-16 px-6 bg-gray-50/50 dark:bg-gray-900/30 border-t border-gray-100 dark:border-gray-800 transition-colors duration-300">
      <div className="max-w-4xl mx-auto">
        <div className="text-center mb-12">
          <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full bg-emerald-100/50 dark:bg-emerald-950/30 text-emerald-800 dark:text-emerald-350 text-sm font-semibold mb-3">
            <Info size={16} />
            <span>Got Questions?</span>
          </div>
          <h2 className="text-3xl font-bold text-gray-900 dark:text-white">
            Frequently Asked Questions
          </h2>
          <p className="mt-3 text-lg text-gray-600 dark:text-gray-400">
            Everything you need to know about the portal access and security.
          </p>
        </div>

        <div className="space-y-4">
          {faqs.map((faq, index) => {
            const isOpen = openIndex === index;
            return (
              <div
                key={index}
                className="bg-white dark:bg-gray-800/60 rounded-xl border border-gray-100 dark:border-gray-700/50 overflow-hidden shadow-xs hover:shadow-md hover:border-gray-200 dark:hover:border-gray-600 transition-all duration-300"
              >
                <button
                  onClick={() => toggleFaq(index)}
                  className="w-full px-6 py-5 flex items-center justify-between text-left font-semibold text-gray-900 dark:text-white hover:text-emerald-600 dark:hover:text-emerald-400 transition-colors"
                >
                  <span>{faq.question}</span>
                  <ChevronDown
                    className={`text-gray-400 shrink-0 transition-transform duration-300 ${
                      isOpen ? 'rotate-180 text-emerald-500' : ''
                    }`}
                    size={20}
                  />
                </button>
                <div
                  className={`transition-all duration-300 ease-in-out overflow-hidden ${
                    isOpen ? 'max-h-60 border-t border-gray-100 dark:border-gray-700/50' : 'max-h-0'
                  }`}
                >
                  <p className="p-6 text-gray-600 dark:text-gray-200 leading-relaxed text-sm bg-gray-50/50 dark:bg-gray-800/30">
                    {faq.answer}
                  </p>
                </div>
              </div>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default FaqSection;
